runtime: nodejs16 # or another supported version

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /images
    static_dir: images

  - url: /fonts/.*
    static_dir: fonts

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto